### ISSUE TITLE
figure out internationalization and localization in JSON-LD for Bioschemas

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon#24]
JSON-LD suggests something like the following, but we need to figure out how that applies Bioschemas:

```json
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "label": {
      "@id": "vocab:label",
      "@container": "@language"
    }
  },
  "@id": "http://example.com/queen",
  "label": {
    "en": "The Queen",
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```

**Comment by philbarker** [comment]
I have been involved in a project that used this approach (ie [language maps](https://json-ld.org/spec/latest/json-ld/#dfn-language-maps)), explored other ideas, and then reverted back to this.
