### ISSUE TITLE
Discussion on introducing Compact Identifiers as Bioschemas type

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon#29]

**Comment by egonw** [comment]
It was discussed with the Compact Identifiers team, and we established that:

1. Compact identifiers are CURIEs are URIs
2. URIs are valid values for the `identifier` property

**Comment by AlasdairGray** [comment]
Did you document this anywhere? Perhaps you can add it to the Bioschemas [wiki](https://github.com/BioSchemas/specifications/wiki/Technical)

**Comment by egonw** [comment]
I added this technical section to the Bioschemas [wiki](https://github.com/BioSchemas/specifications/wiki/Technical): 

![image](https://user-images.githubusercontent.com/26721/48474530-0adf1600-e7fb-11e8-96ee-518a23359b12.png)
