### ISSUE TITLE
bio.tools & EDAM session topics (PLACEHOLDER)

### ISSUE THREAD

**Issue by joncison** [elixir-europe/BioHackathon#3]
This a placeholder issue for discussion around the ["bio.tools & EDAM drop-in hackathon & discussions"](https://github.com/elixir-europe/BioHackathon/tree/master/tools/bio.tools%20%26%20EDAM%20drop-in%20hackathon%20%26%20discussion) session at the ELIXIR BioHackathon (http://bh2018paris.info/) on Nov 12-16.

Please suggest and discuss topics for the event here.

There may be a bit of funding to support travel, for non-ELIXIR people (details tbd)

cc @hmenager  @matuskalas @hansioan @piotrgithub1 @khillion @Ahto123 @krab1k @albangaignard @magnuspalmblad @annalenalamprecht @veitveit @jaanisoe @bgruening 

Please tick here if you'll attend the event (of if you want to but are not listed, ping me here):

- [x] joncison
- [ ] hmenager  
- [ ] matuskalas 
- [ ] hansioan 
- [ ] piotrgithub1 
- [ ] khillion 
- [ ] Ahto123 
- [ ] krab1k 
- [ ] albangaignard 
- [ ] magnuspalmblad 
- [ ] annalenalamprecht 
- [ ] veitveit 
- [ ] jaanisoe 
- [ ] bgruening

**Comment by bgruening** [comment]
* building a developer community around the soon to be open sources bio.tools project (and friends)
  *  Governance
  * Contributing
  * Code of Conduct
* How to integrate crawling and pulling data into bio.tools
  * can we build a plugin-mechanism, so that other communities can write crawlers and annotate tools automatically
* Reviewing all issues and prioritize them

**Comment by joncison** [comment]
heads up  @hmenager @matuskalas @hansioan @piotrgithub1 @khillion @Ahto123 @krab1k @albangaignard @magnuspalmblad @annalenalamprecht @veitveit @jaanisoe @bgruening

the outline of the sessions is done:
https://github.com/elixir-europe/BioHackathon/tree/master/tools/bio.tools%20%26%20EDAM%20drop-in%20hackathon%20%26%20discussions

hope to see some of you there

I included your suggestions Bjoern (2 as hacking topics, one as a "maybe")

**Comment by AlasdairGray** [comment]
@joncison will you be looking to 

1. Expose Bioschemas markup through bio.tools
1. Ingest Bioschemas markup for creating a new entry
1. Generate Bioschemas markup for inclusion on a tool's own web page

**Comment by joncison** [comment]
probably not during the hackathon

In the longer term, **1.** and **3.** for sure, sooner rather than later _assuming_ the Bioschema tool spec is a subset of the biotoolsSchema JSON-LD / RDF-XML serialisation that is already in the pipe (cc @albangaignard @matuskalas) :  ensuring this happens is much easier if I'm leading the Bioschema tool spec activity (as proposed by @rajido, which I'd be happy to do) 

**2.** is a longer-term thing for various reasons
