### ISSUE TITLE
Discuss with Chris adoption of short identifiers with publishers

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon#30]
Needs shorts editorial and chat with BMC.

**Comment by kyook** [comment]
Could you please include me?  I am part of the microPublication.org team focusing on single experiment publications and this seems relevant to us. Thank you.

**Comment by ljgarcia** [comment]
This would be of interest for the Biote-2-Bioschemas creation of profiles for scholarly article and so as well. Did this discussion happen already?

**Comment by Chris-Evelo** [comment]
No, not yet. I just mentioned to Nick Juty that we should indeed talk about it with Manuel, and maybe just write the thing.

**Comment by egonw** [comment]
This has been discussed an a paper is in preparation. Contact Chris Evelo for details.
