### ISSUE TITLE
Can Bioschemas point to RDF of the entity it describes?

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon#41]
Maybe with the sameAs property?

That would provide an alternative to the HTML <link> mechanism to point from a webpage to equivalent RDF.

**Comment by Chris-Evelo** [comment]
probably not sameAs, since RDF often is a structured subset of the data on the page.

**Comment by ljgarcia** [comment]
Do you mean a link between, for instance, a UniProt entry represented in Bioschemas and the purl.org UniProt link? If so, hasCategoryCode or hasDefinedTerm would work, at least that is the idea behing hasCategoryCode in BioChemEntity

**Comment by Chris-Evelo** [comment]
No. I think what was meant is more something like a link between the information about a thing on the actual molecule page on ChEMBL or a pathway page on WIkiPathways, and the RDF the entity for that page available from the SPARQL endpoint for these resources. That RDF could then, of course, have what you described. I don't think the idea was to put the actual RDF in Bioschemas.

**Comment by philbarker** [comment]
Within schema.org I think schema:sameAs is your best match. Yes it should map to the URL of a web page, but a lot of schema.org is oriented around web pages (is an RDF file a web page for machines?? If your target uses content negotiation then it depends who is asking). If you want a more semantically pure approach then you could use a term from another more semantically pure ontology. You can have more than one namespace in your JSON-LD, and applications consuming it should just ignore what the don't understand. So you could use owl:sameAs or wikidata P460 ("said to be the same as") skos:closeMatch depending on how worried you are about collapsing different entities into one.

**Comment by egonw** [comment]
So, here's a use case:

1. https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL471638/ is the webpage about a compound with CHEMBL471638
2. this page has Bioschemas JSON-LD
3. CHEMBL471638 is described in RDF as http://rdf.ebi.ac.uk/resource/chembl/molecule/CHEMBL471638

So, the question is, how can I extend the JSON-LD for that compound (2) on the webpage (1) to point to the RDF (3) and make that machine findable
