### ISSUE TITLE
discuss SMILES in MolecularEntity JSON-LD which requires escaping

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon#47]
And that's not ideal, as we cannot copy verbatim the SMILES into the field value... generators will have to escape characters and clients may need to unescape?

**Comment by egonw** [comment]
When I used EasyRDF to convert the JSON-LD the (escaped) `\\` in the SMILES was preserved... I need to check if `\` needs to be escaped in Turtle too...

**Comment by egonw** [comment]
OK, it seems the `\` needs to be escaped in Turtle too. The specs write:

```
'\' (U+005C) may not appear in any quoted literal except as part of an escape sequence.
```

**Comment by Chris-Evelo** [comment]
Can we use links to smiles instead of actual smiled, or define some kind of package that holds smiles (like we do for phenotype packages)

**Comment by Chris-Evelo** [comment]
I didn't think the package idea completely trough. The idea was to put the actual smile and possibly other info somewhere where it isn't parsed (like give a uuencoded version of it, but there might be better ideas). I guess such a solution will soon get more complicated than escaping. 

Did nobody think of allowing an alternative character in smiles?
